name: smalltalkCI

on: 
  push:
  pull_request:
  schedule:
    - cron: "15 2 5 * *" #run job on the 5th day of every month on the 15th minute of the 2nd hour

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ GemStone64-3.6.1, GemStone64-3.5.6, GemStone64-3.4.5, GemStone64-3.3.9, GemStone64-3.2.17, GemStone64-2.4.8 ]
        experimental: [ false ]
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      # - name: Fix missing OS prerequisites for GemStone builds
      #   run: |
      #     git clone https://github.com/GsDevKit/GsDevKit_home.git
      #     ./GsDevKit_home/bin/utils/installOsPrereqs
      #   continue-on-error: true
      #   if: startsWith(matrix.smalltalk,'GemStone')
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 10
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-18.04
    steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
         with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
          name: 'action run' 
